services:
  backend:
    build:
      context: ./server
    command: uvicorn core.asgi:application --host 0.0.0.0
    ports:
      - 8000:8000
    working_dir: /server
    volumes:
      - ./server:/server
    networks:
      - dpw-red

  frontend:
    build:
      context: ./client
    command: npm start
    ports:
      - 3000:3000
    working_dir: /client
    volumes:
      - ./client:/client
    networks:
      - dpw-red

networks:
  dpw-red:
    driver: bridge
