# Generated by Django 5.1 on 2024-08-14 17:43

import apps.portfolio.models
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('thumbnail', models.ImageField(max_length=1000, upload_to=apps.portfolio.models.project_thumbnail_directory)),
                ('description', models.TextField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('category', models.CharField(choices=[('websites', 'Websites'), ('videogames', 'Videogames')], default='videogames', max_length=25)),
                ('status', models.CharField(choices=[('drafted', 'Drafted'), ('pre_production', 'Pre_production'), ('production', 'Production'), ('finished', 'Finished'), ('constant_updates', 'Constant_updates')], default='drafted', max_length=25)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
            ],
        ),
    ]
