# Generated by Django 4.2.5 on 2024-08-15 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('sp-1', 'Sample category 1'), ('sp-2', 'Sample category 2'), ('sp-3', 'Sample category 3'), ('sp-4', 'Sample category 4')], default='sp-1', max_length=25),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('constant_updates', 'Constant_updates'), ('finished', 'Finished'), ('production', 'Production'), ('pre_production', 'Pre_production')], default='drafted', max_length=25),
        ),
    ]
