# Generated by Django 4.2.5 on 2024-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_category_alter_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('sp-1', 'Sample category 1'), ('sp-4', 'Sample category 4'), ('sp-2', 'Sample category 2'), ('sp-3', 'Sample category 3')], default='sp-1', max_length=25),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('production', 'Production'), ('finished', 'Finished'), ('pre_production', 'Pre_production'), ('drafted', 'Drafted'), ('constant_updates', 'Constant_updates')], default='drafted', max_length=25),
        ),
    ]
