# Generated by Django 4.2.5 on 2024-08-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_category_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('sp-3', 'Sample category 3'), ('sp-2', 'Sample category 2'), ('sp-1', 'Sample category 1'), ('sp-4', 'Sample category 4')], default='sp-1', max_length=25),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pre_production', 'Pre_production'), ('production', 'Production'), ('drafted', 'Drafted'), ('finished', 'Finished'), ('constant_updates', 'Constant_updates')], default='drafted', max_length=25),
        ),
    ]
