export const GET_BLOG_LIST_SUCCESS = "GET_BLOG_LIST_SUCCESS";
export const GET_BLOG_LIST_FAIL = "GET_BLOG_LIST_FAIL";

export const GET_BLOG_FILTER_SUCCESS = "GET_BLOG_FILTER_SUCCESS";
export const GET_BLOG_FILTER_FAIL = "GET_BLOG_FILTER_FAIL";

export const GET_BLOG_LIST_BY_CATEGORIES_SUCCESS =
  "GET_BLOG_LIST_BY_CATEGORIES_SUCCESS";
export const GET_BLOG_LIST_BY_CATEGORIES_FAIL =
  "GET_BLOG_LIST_BY_CATEGORIES_FAIL";

export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_FAIL = "GET_BLOG_FAIL";

export const GET_SEARCH_BLOG_SUCCESS = "GET_SEARCH_BLOG_SUCCESS";
export const GET_SEARCH_BLOG_FAIL = "GET_SEARCH_BLOG_FAIL";

export const GET_AUTHOR_BLOG_SUCCESS = "GET_AUTHOR_BLOG_SUCCESS";
export const GET_AUTHOR_BLOG_FAIL = "GET_AUTHOR_BLOG_FAIL";
