export const GET_PORTFOLIO_LIST_SUCCESS = 'GET_PORTFOLIO_LIST_SUCCESS';
export const GET_PORTFOLIO_LIST_FAIL = 'GET_PORTFOLIO_LIST_FAIL';

export const GET_AUTHOR_PORTFOLIO_LIST_SUCCESS = 'GET_AUTHOR_PORTFOLIO_LIST_SUCCESS';
export const GET_AUTHOR_PORTFOLIO_LIST_FAIL = 'GET_AUTHOR_PORTFOLIO_LIST_FAIL';

export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAIL = 'GET_PROJECT_FAIL';